services:
  - type: web
    name: tuition-centre-booking
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
